In [1]:
import gym
import numpy as np
import random 
import time 
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
num_episodes = 50000
max_steps_per_episode = 500
learning_rate = 0.01
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [5]:
rewards_all_episodes = []

#Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        # Exploration and Exploitation Trade off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else: 
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        #Update Q_table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate *(reward + discount_rate * np.max(q_table[new_state,:]))
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
        
    #Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate)* np.exp(- exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)

    
# calculating and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("**************Average reward per thousand episodes***********\n")
for r in rewards_per_thousand_episodes:
    print(count,": ", str(sum(r/1000)))
    count += 1000
    
#Print updated Q-table
print("\n\n**********Q-table********\n")
print(q_table)
    

**************Average reward per thousand episodes***********

1000 :  0.027000000000000017
2000 :  0.047000000000000035
3000 :  0.057000000000000044
4000 :  0.047000000000000035
5000 :  0.06700000000000005
6000 :  0.05500000000000004
7000 :  0.05300000000000004
8000 :  0.05000000000000004
9000 :  0.046000000000000034
10000 :  0.05400000000000004
11000 :  0.06900000000000005
12000 :  0.058000000000000045
13000 :  0.06300000000000004
14000 :  0.04900000000000004
15000 :  0.05100000000000004
16000 :  0.06100000000000005
17000 :  0.06400000000000004
18000 :  0.06300000000000004
19000 :  0.05500000000000004
20000 :  0.05400000000000004
21000 :  0.04400000000000003
22000 :  0.05400000000000004
23000 :  0.04900000000000004
24000 :  0.06100000000000005
25000 :  0.06300000000000004
26000 :  0.06400000000000004
27000 :  0.057000000000000044
28000 :  0.060000000000000046
29000 :  0.09500000000000007
30000 :  0.10100000000000008
31000 :  0.08600000000000006
32000 :  0.09800000000000007
33000 :  0

In [6]:
for episode in range(3):
    state = env.reset()
    done = False
    print("***********EPISODE ", episode +1,"******\n\n\n")
    time.sleep(3)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done == True:
            clear_output(wait =True)
            env.render()
            if reward == 1:
                print("******** You reached your goal**********")
                time.sleep(3)
            else:
                print("******* You fell into a hole*******")
                time.sleep(3)
            clear_output(wait = True)
            break
        state = new_state
        
        
env.close()
    

  (Right)
SFFF
FHFH
FFFH
HFFG
******* You fell into a hole*******
